### ISSUE TITLE
typos in sentence.csv

### ISSUE THREAD

**Issue by fadouaabdoul** [darija-open-dataset/dataset#65]
I've been looking through the sentence.csv and found out that they are some typos in some sentences like using "8" as " h" or "7", and also they are some sentences that can have a variant of translated sentences for example: " kaychrab kass dyal lma" as " kaychrb kass dlma" 
In addition, the use of "x" instead of "ch".

![image](https://user-images.githubusercontent.com/54518948/233911143-9cca4ec7-6ff2-4384-99e9-fb76283620ca.png)

**Comment by darija-open-dataset** [comment]
Thanks Fadoua, will check that

**Comment by fadouaabdoul** [comment]
If it is possible I can contribute to this repo by fixing these kind of typos, if so can we discuss further more about the second problem of having variant sentences?

**Comment by darija-open-dataset** [comment]
Yeah ofc, that would be very helpful :D Contributions are always welcome and appreciated. Thanks :)
For the second point, the obvious way to handle it would be to just add as many variations as possible. Otherwise, if you have any suggestions we're open to exploring them.

Thank you again Fadoua for your willingness to help improve the project!
